pub use zcode_cli_protocol as protocol;

pub mod agent_profile;
pub mod attachment_upload;
pub mod background;
pub mod claude_import;
pub mod config;
pub mod context;
pub mod edit_match;
pub mod execution;
pub mod file_checkpoint;
pub mod goal;
pub mod history;
pub mod hooks;
pub mod js_string;
pub mod json_order;
mod json_size;
pub mod legacy_attachments;
pub mod legacy_goal;
pub mod legacy_input_params;
pub mod legacy_params;
pub mod legacy_snapshot;
pub mod legacy_stream;
pub mod model;
pub mod option_map;
pub mod permission;
pub mod persisted_output;
pub mod plan_mode;
pub mod prompt;
pub mod question;
mod question_answer;
pub mod row_page;
pub mod session;
pub mod session_debug;
pub mod session_listing;
mod session_memory;
pub mod session_projection;
mod session_recovery;
pub mod session_runtime;
pub mod shared_context;
pub mod shared_import;
pub mod skills;
pub mod subagent;
mod subagent_row;
pub mod todo;
pub mod web;
pub mod zod;

pub const MAX_REQUEST_BYTES: usize = 1024 * 1024;
pub const MAX_TEXT_BYTES: usize = 256 * 1024;
pub const MAX_TOOL_BYTES: usize = 64 * 1024;
pub const MAX_QUEUE: usize = 32;
